server:
  port: 8080
#  ssl:
#    key-store-type: PKCS12
#    key-store: classpath:keystore.p12
#    key-store-password: esterco_full
#    key-alias: myalias
#    enabled: true

spring:
  application:
    name: automated-restaurant-backend
  datasource:
    driverClassName: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: postgres
#    password: 123
    url: jdbc:postgresql://golden-cash-bunny-db.c1k8ckseaan4.us-east-2.rds.amazonaws.com:5432/initial_db
    username: postgres
    password: eridogisthemaster
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none

feign:
  okhttp:
    enabled: true